/**
 * Campaign definition.
 *
 * Every act races APEX International — the circuit generated by
 * `game/track/layout` — in daylight. Levels retain their progression, scoring,
 * rival, and surface-grip differences; the geometry and the palette are shared.
 */

import type { CarId } from "./cars";

/**
 * Playable levels.
 *
 * Two acts, deliberately. They are the complete argument the game exists to make:
 * Act I puts a run on the Settlement Layer so the player feels the wait, and Act II
 * hands it to an Ephemeral Session so they feel the wait disappear. Problem, then
 * solution. Everything after that was elaboration on a point already made.
 *
 * The acts that used to follow — tick rate, the commit window, undelegate — are
 * retired rather than deleted: their on-chain indices are reserved in
 * `LEVEL_INDEX`, and the campaign advertises the next one as a roadmap card. See
 * `COMING_SOON_ACT`.
 */
export type LevelId = "act1-harbor" | "act2-neon-mile";

/**
 * Colours for the generated circuit.
 *
 * Every trackside surface is vertex-coloured from this palette, so the whole
 * 5.86km lap renders from one material with no textures to download. Re-theming
 * the circuit is editing this object.
 */
export interface CityPalette {
  /** The racing surface. */
  asphalt: number;
  /** Kerb stripes, alternating along the road edge through corners. */
  kerbLight: number;
  kerbDark: number;
  /** Concrete barrier body and its painted top cap. */
  barrier: number;
  barrierTop: number;
  /** Sealed run-off immediately behind the barrier. */
  plaza: number;
  /** Where the run-off meets the surrounding ground. */
  verge: number;
  /** Lighting columns, gantries and fence posts. */
  steel: number;
  /** Painted road markings. */
  line: number;
  /**
   * Barrier light strip, and the same strip through a corner warning.
   *
   * Drawn unlit and outside tone mapping, so these are the only two colours in
   * the palette that read as emitted rather than reflected light. `ledWarn`
   * replaces `led` from the advance board through to the corner exit, which is
   * what makes an approaching corner visible before its geometry is.
   */
  led: number;
  ledWarn: number;
}

/** One stop in the vertical sky gradient. `at` runs 0 at the horizon to 1 overhead. */
export interface SkyStop {
  at: number;
  color: number;
}

export interface LevelEnvironment {
  /**
   * Vertical sky gradient, horizon first.
   *
   * A stop list rather than two endpoint colours. Two colours can only ever
   * produce a linear wash, which is what made the old sky read as flat paint; real
   * daylight is warm and bright at the horizon, pales through the middle, and
   * deepens overhead. The dome interpolates between whatever stops are given, so
   * re-theming the sky is editing this list.
   */
  sky: readonly SkyStop[];
  fog: number;
  /** Exponential fog density. Higher hides more distance = cheaper draw. */
  fogDensity: number;
  ground: number;
  sunColor: number;
  sunIntensity: number;
  /** Sun elevation/azimuth, radians. */
  sunElevation: number;
  sunAzimuth: number;
  ambient: number;
  ambientIntensity: number;
  /** Readable blue accent for daylight HUD and status details. */
  accent: number;
  city: CityPalette;
}

export interface StoryBeat {
  speaker: "HALO" | "KESTREL" | "VALIDATOR" | "SYSTEM";
  line: string;
  /** When to show it: before the countdown, on a given lap, or at the finish. */
  at: "pre" | "start" | "finish" | number;
}

export interface LevelDefinition {
  id: LevelId;
  act: number;
  /** Short code shown in the level list, e.g. "ACT I". */
  actLabel: string;
  title: string;
  /**
   * Event type, and what makes this round different to drive.
   *
   * Player-facing race copy, so it is written the way a racing game writes it. The
   * rollup mechanics behind a round live in `erEnabled` and `bankingEnabled` and are
   * explained on the landing page — a driver picking a round wants to know the grid
   * size and the surface, not the transaction model.
   */
  concept: string;
  conceptDetail: string;
  laps: number;
  rivals: number;
  /** Target time in ms. XP scales against this. */
  parMs: number;
  /** Fastest physically plausible time. The program rejects anything below. */
  floorMs: number;
  baseXp: number;
  driftMultiplier: number;
  cleanBonus: number;
  /** Act III gate: minimum drift score to pass. 0 = no gate. */
  driftTarget: number;
  /** Placing needed to clear the level. */
  targetPosition: number;
  /** Act I runs on the base layer only, to make the contrast felt. */
  erEnabled: boolean;
  /** Act IV: player may commit at each lap for an escalating risk multiplier. */
  bankingEnabled: boolean;
  /** Act V: rival AI runs at full skill with no rubber-banding. */
  bossRace: boolean;
  /** Driver XP required to unlock. */
  unlockXp: number;
  recommendedCar: CarId;
  /** Surface grip multiplier; geometry always comes from the supplied map. */
  gripScale: number;
  env: LevelEnvironment;
  story: StoryBeat[];
}

/**
 * APEX International at sunset, on a high desert plateau.
 *
 * A low sun almost on the deck, a sky that runs amber at the horizon into dusk
 * overhead, and enough haze that the generated mesa horizon reads as distance
 * rather than as geometry parked at the far plane. The same gradient feeds the
 * image-based lighting, so the car's metallic paint picks up the sunset instead
 * of rendering near-black.
 *
 * `fogDensity` is roughly three times the old daylight value. `FogExp2` falls off
 * with the *square* of `density * distance`, so 0.00062 was doing almost nothing
 * at any distance the camera can see — 8% at 560m — and the horizon sat there
 * unhazed and looked like a wall.
 */
export const DESERT_SUNSET: LevelEnvironment = {
  // Amber on the deck, deepening to dusk overhead. The horizon stop is close to
  // the fog colour so the two meet without a seam.
  sky: [
    { at: 0, color: 0xffd9a3 },
    { at: 0.05, color: 0xffb268 },
    { at: 0.16, color: 0xfb8f4c },
    { at: 0.42, color: 0xdd6242 },
    { at: 1, color: 0x5d3f6b },
  ],
  fog: 0xf2a468,
  fogDensity: 0.0016,
  ground: 0x6d4d35,
  sunColor: 0xffb877,
  sunIntensity: 2.35,
  // 9° above the horizon: long shadows across the road, which is most of what
  // sells the time of day.
  sunElevation: 0.16,
  sunAzimuth: -1.95,
  ambient: 0xffcda6,
  ambientIntensity: 1.0,
  accent: 0x2ee06a,
  city: {
    asphalt: 0x2c2f34,
    kerbLight: 0xf2f4f7,
    kerbDark: 0xcf3340,
    barrier: 0x23262c,
    barrierTop: 0x14161a,
    plaza: 0x8b7154,
    verge: 0x6d4d35,
    steel: 0x8b929d,
    line: 0xf7f9fb,
    led: 0x3bff8c,
    ledWarn: 0xffb32e,
  },
};

/**
 * Act I: the same plateau earlier in the evening, hazier and less saturated.
 *
 * The opening act used to load a photographic backdrop. A 1.6:1 photograph is not
 * a panorama, so it had to be wrapped three times around a cylinder, and the seam
 * between wraps showed as a hard vertical edge against the sky. A gradient has no
 * seam, no download, and no horizon to keep level.
 */
export const DESERT_HAZE: LevelEnvironment = {
  ...DESERT_SUNSET,
  sky: [
    { at: 0, color: 0xffe6bd },
    { at: 0.06, color: 0xffc98d },
    { at: 0.2, color: 0xf6a469 },
    { at: 0.48, color: 0xd97f57 },
    { at: 1, color: 0x6f5578 },
  ],
  fog: 0xf6bd8b,
  fogDensity: 0.0018,
  sunColor: 0xffd0a0,
  sunElevation: 0.21,
  ambient: 0xffe0c2,
};

export const LEVELS: Record<LevelId, LevelDefinition> = {
  "act1-harbor": {
    id: "act1-harbor",
    act: 1,
    actLabel: "ACT I",
    title: "Cold Start",
    concept: "Season opener",
    conceptDetail:
      "One lap of APEX International against a light grid. Learn where the circuit climbs, where it drops, and how late the hairpin really lets you brake.",
    laps: 1,
    rivals: 3,
    parMs: 94000,
    floorMs: 58500,
    baseXp: 400,
    driftMultiplier: 0.04,
    cleanBonus: 150,
    driftTarget: 0,
    targetPosition: 3,
    erEnabled: false,
    bankingEnabled: false,
    bossRace: false,
    unlockXp: 0,
    recommendedCar: "zagato",
    gripScale: 1,
    env: DESERT_HAZE,
    story: [
      {
        speaker: "HALO",
        at: "pre",
        line: "Cold tyres, cold engine, cold driver. One lap. Just bring it back in one piece.",
      },
      {
        speaker: "HALO",
        at: "finish",
        line: "That'll do. You lost the most time in the hairpin — you're braking about twenty metres early.",
      },
    ],
  },

  "act2-neon-mile": {
    id: "act2-neon-mile",
    act: 2,
    actLabel: "ACT II",
    title: "Slipstream",
    concept: "Full grid",
    conceptDetail:
      "A full grid of five, and two straights long enough for a tow. Sit in the car ahead down the pit straight and you arrive at turn one with a run on it.",
    laps: 1,
    rivals: 5,
    parMs: 94000,
    floorMs: 58500,
    baseXp: 700,
    driftMultiplier: 0.06,
    cleanBonus: 250,
    driftTarget: 0,
    targetPosition: 3,
    erEnabled: true,
    bankingEnabled: false,
    bossRace: false,
    unlockXp: 0,
    recommendedCar: "zagato",
    gripScale: 1,
    env: DESERT_SUNSET,
    story: [
      {
        speaker: "HALO",
        at: "pre",
        line: "Full grid this time. Five of them, and the two quick ones start ahead of you.",
      },
      {
        speaker: "HALO",
        at: "start",
        line: "Green. Get in the tow down the straight and you'll have a run into turn one.",
      },
      {
        speaker: "HALO",
        at: "finish",
        line: "Clean enough. Bank the run and it's on the board for good.",
      },
    ],
  },
};

export const CAMPAIGN_ORDER: LevelId[] = ["act1-harbor", "act2-neon-mile"];

export const LEVEL_IDS = Object.keys(LEVELS) as LevelId[];

/**
 * Stable index used by the on-chain program (u8). Order must never change.
 *
 * Indices 2 to 5 belonged to the retired acts and to Time Attack. They are
 * deliberately left unassigned rather than reused: a `DriverProfile` PDA already on
 * chain records cleared levels by index, so handing index 2 to a different level
 * would silently mark it cleared for every existing player.
 * `programs/apex_racing/src/xp.rs` keeps its parameters for the same reason.
 */
export const LEVEL_INDEX: Record<LevelId, number> = {
  "act1-harbor": 0,
  "act2-neon-mile": 1,
};

/**
 * The roadmap card the campaign shows after the playable acts.
 *
 * Not a `LevelDefinition`: it has no par time, no rival count and nothing to race,
 * and giving it one would mean a level that exists in the type system, ships in the
 * route table and cannot be played. A separate shape keeps "announced" and
 * "playable" impossible to confuse.
 */
export interface ComingSoonAct {
  actLabel: string;
  title: string;
  concept: string;
  conceptDetail: string;
}

export const COMING_SOON_ACT: ComingSoonAct = {
  actLabel: "ACT III",
  title: "Drift Trial",
  concept: "Drift scoring",
  conceptDetail:
    "A scored round rather than a race. Hold the car sideways through the esses and the hairpin, and the longer the angle holds the more the corner pays.",
};

export function isLevelId(value: string): value is LevelId {
  return value in LEVELS;
}

export function getLevel(id: string): LevelDefinition | undefined {
  return isLevelId(id) ? LEVELS[id] : undefined;
}

export function levelFromIndex(index: number): LevelDefinition | undefined {
  const id = LEVEL_IDS.find((l) => LEVEL_INDEX[l] === index);
  return id ? LEVELS[id] : undefined;
}
