#!/usr/bin/env node
/**
 * Fail-fast runtime asset report.
 *
 * The two car GLBs are the only 3D payloads a race downloads — the circuit is
 * generated at load, so there is no map asset to check. Budgets cover the costs
 * that actually stall a first frame: download size, draw calls, vertex work,
 * image decode count, and uncompressed texture memory including mipmaps.
 *
 * The rig count is checked too, because a player car that quietly loses its
 * `WHEEL_**` groups during optimisation still looks correct parked on the grid
 * and never turns a wheel once moving.
 */

import { readFile, stat } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { NodeIO } from "@gltf-transform/core";
import { ALL_EXTENSIONS } from "@gltf-transform/extensions";
import draco3d from "draco3dgltf";
import { collectAssetHashes, MANIFEST_PATH } from "./lib/asset-manifest.mjs";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const MB = 1024 * 1024;

const RIG_NODES = [/^WHEEL_LF/i, /^WHEEL_RF/i, /^WHEEL_LR/i, /^WHEEL_RR/i, /^STEER_HR/i];

/**
 * Tyre materials, which must not ship metallic.
 *
 * The source exports both tyre carcasses with `metallicFactor: 1.0`. A fully
 * metallic surface under image-based lighting reflects the sky rather than shading,
 * so the tyre rendered as a chrome ring and the wheel looked like a bare rim with
 * the rubber missing. `optimize-assets` corrects it; this is the check that the
 * correction actually reached the shipped bytes.
 */
const RUBBER_MATERIAL = /^(EXT_WHEEL|EXT_TYRE|tyre|tire|rubber)/i;
const RUBBER_MAX_METALNESS = 0.05;

/**
 * glTF extensions three.js decodes without a plugin loader.
 *
 * `Resources` deliberately builds a bare `GLTFLoader` — no `DRACOLoader`, no
 * `KTX2Loader` — so anything the pipeline emits has to be on this list. When the
 * two disagreed, every car silently fell back to a blocked-out placeholder box and
 * the only clue was a console line, because a GLTFLoader that is handed a
 * Draco-compressed primitive with no decoder simply rejects.
 */
const NATIVE_EXTENSIONS = new Set([
  "KHR_mesh_quantization",
  "KHR_texture_transform",
  "KHR_materials_clearcoat",
  "KHR_materials_emissive_strength",
  "KHR_materials_ior",
  "KHR_materials_sheen",
  "KHR_materials_specular",
  "KHR_materials_transmission",
  "KHR_materials_unlit",
  "KHR_materials_volume",
  "KHR_lights_punctual",
  "KHR_texture_basisu",
  "EXT_texture_webp",
  "EXT_meshopt_compression",
]);

const ASSETS = [
  {
    label: "zagato.glb",
    note: "player · rigged",
    path: join(ROOT, "public", "models", "cars", "zagato.glb"),
    rig: RIG_NODES.length,
    rubber: true,
    tyres: true,
    budget: { bytes: 5 * MB, primitives: 56, vertices: 160_000, textures: 24, vram: 22 * MB },
  },
  {
    label: "zagato-lq.glb",
    // Only the `low` tier now. Its rig is collapsed, so any car using it has
    // wheels welded to the bodyshell — see `carDetailFor`. Above `low` the whole
    // field shares the rigged variant, which is also one fewer download.
    note: "low tier only · rig collapsed",
    path: join(ROOT, "public", "models", "cars", "zagato-lq.glb"),
    rig: 0,
    rubber: true,
    budget: { bytes: 2 * MB, primitives: 34, vertices: 70_000, textures: 24, vram: 12 * MB },
  },
  // Intact roadside trees. Runtime clones share these resources, but each placement
  // is a separate frustum-cullable object. Exact topology is an integrity contract,
  // not merely a budget: a reduced or rewired tree must fail this report even if it
  // is smaller and faster. Source/candidate bounds and triangle-shape comparisons
  // are additionally enforced by `optimize-scenery.mjs` before publication.
  {
    label: "tree-conifer.glb",
    note: "intact · individual shared clones",
    path: join(ROOT, "public", "models", "env", "tree-conifer.glb"),
    rig: 0,
    topology: { primitives: 8, vertices: 46_269, triangles: 42_831 },
    budget: { bytes: 2.5 * MB, primitives: 8, vertices: 46_269, textures: 8, vram: 3 * MB },
  },
  {
    label: "tree-poplar.glb",
    note: "intact · individual shared clones",
    path: join(ROOT, "public", "models", "env", "tree-poplar.glb"),
    rig: 0,
    topology: { primitives: 9, vertices: 127_825, triangles: 108_056 },
    budget: { bytes: 7.25 * MB, primitives: 9, vertices: 127_825, textures: 11, vram: 3 * MB },
  },
  {
    label: "tree-poinciana.glb",
    note: "intact · individual shared clones",
    path: join(ROOT, "public", "models", "env", "tree-poinciana.glb"),
    rig: 0,
    topology: { primitives: 11, vertices: 315_243, triangles: 323_555 },
    budget: { bytes: 17 * MB, primitives: 11, vertices: 315_243, textures: 16, vram: 4 * MB },
  },
  {
    label: "landscape.glb",
    // No longer loaded: the horizon is generated by `src/game/world/horizon.ts`,
    // which is why the temperate forest range could be swapped for a high desert
    // one without an asset pipeline run. Kept on disk and still budget-checked so
    // it remains a usable backdrop, but it is dead weight in `public/` until it is
    // either wired back up or deleted.
    note: "retained, not loaded · horizon is generated",
    path: join(ROOT, "public", "models", "env", "landscape.glb"),
    rig: 0,
    // Every ground, forest-card, hill, and mountain triangle survives. The sole
    // source exclusion is Sketchfab's finite Material.011 panorama preview dome.
    topology: { primitives: 9, vertices: 34_653, triangles: 17_640 },
    forbiddenNodes: ["Sphere_Material.011_0"],
    forbiddenMaterials: ["Material.011"],
    budget: { bytes: 2.1 * MB, primitives: 9, vertices: 34_653, textures: 13, vram: 12 * MB },
  },
];

function formatBytes(bytes) {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < MB) return `${Math.round(bytes / 1024)} KB`;
  return `${(bytes / MB).toFixed(2)} MB`;
}

function tyreTopology(root) {
  const tyres = [];
  for (const pattern of RIG_NODES.slice(0, 4)) {
    const wheel = root.listNodes().find((node) => pattern.test(node.getName()));
    if (!wheel) continue;
    const pending = [wheel];
    let triangles = 0;
    while (pending.length > 0) {
      const node = pending.pop();
      if (!node) continue;
      pending.push(...node.listChildren());
      for (const primitive of node.getMesh()?.listPrimitives() ?? []) {
        if (!RUBBER_MATERIAL.test(primitive.getMaterial()?.getName() ?? "")) continue;
        const positions = primitive.getAttribute("POSITION")?.getCount() ?? 0;
        triangles += Math.floor((primitive.getIndices()?.getCount() ?? positions) / 3);
      }
    }
    tyres.push({ wheel: wheel.getName(), triangles });
  }
  return tyres;
}

function overages(asset, cost) {
  const b = asset.budget;
  const failures = [];
  if (cost.bytes > b.bytes) failures.push(`size ${formatBytes(cost.bytes)} > ${formatBytes(b.bytes)}`);
  if (cost.primitives > b.primitives) failures.push(`primitives ${cost.primitives} > ${b.primitives}`);
  if (cost.vertices > b.vertices) {
    failures.push(`vertices ${cost.vertices.toLocaleString("en-US")} > ${b.vertices.toLocaleString("en-US")}`);
  }
  if (cost.textures > b.textures) failures.push(`textures ${cost.textures} > ${b.textures}`);
  if (cost.vram > b.vram) failures.push(`VRAM ${formatBytes(cost.vram)} > ${formatBytes(b.vram)}`);
  if (cost.rig !== asset.rig) failures.push(`rig ${cost.rig} != ${asset.rig} expected`);
  if (asset.topology) {
    for (const key of ["primitives", "vertices", "triangles"]) {
      if (cost[key] !== asset.topology[key]) {
        failures.push(
          `${key} ${cost[key].toLocaleString("en-US")} != ` +
            `${asset.topology[key].toLocaleString("en-US")} intact source`,
        );
      }
    }
  }
  if (asset.rubber) {
    if (cost.rubber.length === 0) failures.push("no tyre material found");
    for (const tyre of cost.rubber) {
      if (tyre.metalness > RUBBER_MAX_METALNESS) {
        failures.push(`${tyre.name} is ${tyre.metalness.toFixed(2)} metallic — rubber is not metal`);
      }
    }
  }
  if (asset.tyres) {
    if (cost.tyres.length !== 4) failures.push(`${cost.tyres.length}/4 tyre carcasses found`);
    for (const tyre of cost.tyres) {
      if (tyre.triangles < 1_800) {
        failures.push(`${tyre.wheel} tyre has only ${tyre.triangles} triangles`);
      }
    }
  }
  for (const name of asset.forbiddenNodes ?? []) {
    if (cost.nodes.includes(name)) failures.push(`forbidden preview node ${name} is still shipped`);
  }
  for (const name of asset.forbiddenMaterials ?? []) {
    if (cost.materials.includes(name)) {
      failures.push(`forbidden preview material ${name} is still shipped`);
    }
  }
  for (const extension of cost.required) {
    if (!NATIVE_EXTENSIONS.has(extension)) {
      failures.push(`requires ${extension}, which the runtime loader cannot decode`);
    }
  }
  return failures;
}

/**
 * Read `extensionsRequired` from the GLB's JSON chunk directly.
 *
 * gltf-transform decodes compression on read, so the parsed Document no longer
 * reports it — the only honest source is the bytes the browser will be handed.
 */
/**
 * The generated manifest must match the bytes on disk.
 *
 * A stale hash is worse than no hash: it re-points the URL at a cache entry for
 * different contents, which is precisely the failure the manifest exists to
 * prevent.
 */
async function checkManifest() {
  let manifest;
  try {
    manifest = JSON.parse(await readFile(MANIFEST_PATH, "utf8"));
  } catch {
    console.error(`\n  Missing ${MANIFEST_PATH} — run npm run assets:optimize`);
    return 1;
  }

  // Compare against a fresh scan rather than a hardcoded list, so an asset added
  // to `public/` without regenerating the manifest is caught too — a missing entry
  // silently reverts that one file to un-bustable caching.
  const actual = await collectAssetHashes();
  const recorded = manifest.assets ?? {};
  let failures = 0;

  for (const [url, hash] of Object.entries(actual)) {
    if (recorded[url] === hash) continue;
    console.error(
      `  ${url}: manifest says v=${recorded[url] ?? "(absent)"} but the file hashes ` +
        `to v=${hash} — run npm run assets:optimize`,
    );
    failures += 1;
  }
  for (const url of Object.keys(recorded)) {
    if (url in actual) continue;
    console.error(`  ${url}: in the manifest but no longer on disk`);
    failures += 1;
  }

  if (failures === 0) {
    console.log(`  manifest             ${Object.keys(actual).length} assets, all hashes current`);
  }
  return failures;
}

async function requiredExtensions(path) {
  const bytes = await readFile(path);
  const jsonLength = bytes.readUInt32LE(12);
  const json = JSON.parse(bytes.subarray(20, 20 + jsonLength).toString("utf8"));
  return json.extensionsRequired ?? [];
}

async function main() {
  const io = new NodeIO()
    .registerExtensions(ALL_EXTENSIONS)
    .registerDependencies({ "draco3d.decoder": await draco3d.createDecoderModule() });

  console.log(
    `\n  ${"runtime asset".padEnd(16)}${"size".padStart(9)}${"prims".padStart(7)}` +
      `${"verts".padStart(9)}${"tex".padStart(5)}${"vram".padStart(9)}${"rig".padStart(5)}   note\n` +
      `  ${"-".repeat(78)}`,
  );

  let failures = 0;
  for (const asset of ASSETS) {
    const [file, document] = await Promise.all([stat(asset.path), io.read(asset.path)]);
    const root = document.getRoot();

    let primitives = 0;
    let vertices = 0;
    let triangles = 0;
    for (const mesh of root.listMeshes()) {
      for (const primitive of mesh.listPrimitives()) {
        primitives += 1;
        const positionCount = primitive.getAttribute("POSITION")?.getCount() ?? 0;
        vertices += positionCount;
        triangles += Math.floor((primitive.getIndices()?.getCount() ?? positionCount) / 3);
      }
    }
    const textures = root.listTextures();
    const vram = textures.reduce((total, texture) => {
      const [width, height] = texture.getSize() ?? [0, 0];
      return total + width * height * 4 * 1.33;
    }, 0);
    const rig = RIG_NODES.filter((pattern) =>
      root.listNodes().some((node) => pattern.test(node.getName())),
    ).length;
    const rubber = root
      .listMaterials()
      .filter((material) => RUBBER_MATERIAL.test(material.getName()))
      .map((material) => ({
        name: material.getName(),
        metalness: material.getMetallicFactor(),
      }));

    const required = await requiredExtensions(asset.path);
    const cost = {
      bytes: file.size,
      primitives,
      vertices,
      triangles,
      textures: textures.length,
      vram,
      rig,
      rubber,
      tyres: tyreTopology(root),
      nodes: root.listNodes().map((node) => node.getName()),
      materials: root.listMaterials().map((material) => material.getName()),
      required,
    };
    const exceeded = overages(asset, cost);
    failures += exceeded.length;

    console.log(
      `  ${asset.label.padEnd(16)}${formatBytes(cost.bytes).padStart(9)}` +
        `${String(cost.primitives).padStart(7)}${cost.vertices.toLocaleString("en-US").padStart(9)}` +
        `${String(cost.textures).padStart(5)}${formatBytes(cost.vram).padStart(9)}` +
        `${String(cost.rig).padStart(5)}   ${asset.note}` +
        (exceeded.length > 0 ? `\n      ${exceeded.join(", ")}` : ""),
    );
  }

  failures += await checkManifest();

  if (failures > 0) {
    console.error(`\n  Runtime asset budgets failed (${failures} overage${failures === 1 ? "" : "s"}).\n`);
    process.exitCode = 1;
  } else {
    console.log(
      "\n  All runtime assets within budget, natively decodable, cache-busted, " +
        "and the player car's rig intact.\n",
    );
  }
}

await main();
