/**
 * Anchor discriminators for `apex_racing`.
 *
 * Generated by `node scripts/discriminators.mjs` — regenerate and paste after
 * adding or renaming any instruction. Hardcoding these lets the client build
 * transactions with a hand-rolled Borsh writer instead of shipping an IDL plus
 * an Anchor `Program` instance, which keeps roughly 200KB out of the bundle.
 */

export const IX = {
  initializeDriver: new Uint8Array([80, 77, 87, 234, 229, 221, 217, 13]),
  openSession: new Uint8Array([130, 54, 124, 7, 236, 20, 104, 104]),
  delegateSession: new Uint8Array([82, 83, 119, 119, 196, 219, 5, 197]),
  tick: new Uint8Array([92, 79, 44, 8, 101, 80, 63, 15]),
  finishRace: new Uint8Array([174, 118, 135, 231, 103, 31, 171, 94]),
  bankRun: new Uint8Array([63, 156, 75, 60, 134, 47, 71, 188]),
  settleRun: new Uint8Array([131, 162, 190, 83, 221, 20, 93, 149]),
  claimXp: new Uint8Array([21, 122, 110, 182, 181, 76, 140, 47]),
  abandonSession: new Uint8Array([220, 175, 61, 59, 8, 238, 143, 249]),
} as const;

export const ACCOUNT = {
  driverProfile: new Uint8Array([116, 172, 75, 50, 68, 157, 48, 16]),
  raceSession: new Uint8Array([221, 113, 245, 11, 7, 80, 172, 26]),
} as const;

export function discriminatorMatches(data: Uint8Array, expected: Uint8Array): boolean {
  if (data.length < 8) return false;
  for (let i = 0; i < 8; i += 1) {
    if (data[i] !== expected[i]) return false;
  }
  return true;
}
